### ISSUE TITLE
Bug #4 -- controls don't work

### ISSUE THREAD

**Issue by MJP8** [MJP8/object#12]
**Describe the bug**
I switched the `div` elements with JavaScript styles to images, but now the controls don't work.

**To Reproduce**
1. Go to ['192.168.7.33/object/'](http://192.168.7.33/object/)
2. See error

**Expected behavior**
I expected the images to move around like the `div`s used to. This is the [JS] (here's the [HTML]).

/cc @elijahparker 

[JS]: https://github.com/MJP8/object/blob/object-oriented-javascript/game.js
[HTML]: https://github.com/MJP8/object/blob/object-oriented-javascript/game.js

**Comment by elijahparker** [comment]
It might be best just to wrap the img tag in a div, since img has less options than div.

**Comment by MJP8** [comment]
I already tried that but I'll try again.

**Comment by MJP8** [comment]
If I do that this is [the result].

/cc @elijahparker 

[the result]: http://192.168.7.33/object/

**Comment by MJP8** [comment]
Same JS, different HTML (use the first links for JS and HTML).

**Comment by elijahparker** [comment]
Another option is to go back to just the div like you had before, but make the image the background image in css (and set the div to the right size for the image)

**Comment by MJP8** [comment]
It didn't work. Now they are invisible.

**Comment by MJP8** [comment]
Never mind. I need to specify the height too.

**Comment by MJP8** [comment]
They just won't move still.

**Comment by MJP8** [comment]
Specifying `position: absolute;` in the CSS worked! (c608ab1419ef89982638ee684fcadad8ef6bf31b).
